Updated install location

diff --git a/install b/install
--- a/install
+++ b/install
@@ -2,27 +2,43 @@
 
 set -e
 
-export INSTALL_LOG="/var/log/remotelabz/install.log"
+export INSTALL_LOG="/var/log/remotelabz-worker/install.log"
+
+function debug() {
+    echo "[$(date -u)] $1" >> "${INSTALL_LOG}" 2>&1
+}
+
+function warning() {
+    echo -ne "\e[33m" >> "${INSTALL_LOG}" 2>&1
+    echo -n "[$(date -u)] WARN: $1" >> "${INSTALL_LOG}" 2>&1
+    echo -e "\e[39m" >> "${INSTALL_LOG}" 2>&1
+}
 
 function error() {
+    echo -ne "\e[31m" >> "${INSTALL_LOG}" 2>&1
+    echo -n "[$(date -u)] ERROR: $1" >> "${INSTALL_LOG}" 2>&1
+    echo -e "\e[39m" >> "${INSTALL_LOG}" 2>&1
+}
+
+function quit_on_error() {
   echo "Error ❌"
   echo "Please check logs in ${INSTALL_LOG} to see what went wrong. Exiting..."
   exit 1
 }
 
-trap 'error' ERR
+trap 'quit_on_error' ERR
+
+debug "Starting remoteLabz-worker installation"
 
 # Check for root
 if [ "$(whoami)" != "root" ]; then
+    error "Installation aborted, root is required!"
     echo "ERROR: This script must be executed as root! We need to hack some things on your computer. 😎"
     exit 1
 fi
 
-while getopts "d:p:" opt; do
+while getopts "p:" opt; do
   case $opt in
-    d)
-      export REMOTELABZ_WORKER_PATH="$OPTARG"
-      ;;
     p)
       export REMOTELABZ_WORKER_PORT="$OPTARG"
       ;;
@@ -39,7 +55,7 @@ done
 
 # Environment variables
 if [ -z "$REMOTELABZ_WORKER_PATH" ]; then
-    export REMOTELABZ_WORKER_PATH=/var/www/html/remotelabz-worker
+    export REMOTELABZ_WORKER_PATH=/opt/remotelabz-worker
 fi
 if [ -z "$REMOTELABZ_WORKER_PORT" ]; then
     export REMOTELABZ_WORKER_PORT=8080
@@ -54,6 +70,7 @@ HAS_MOVED=0
 mkdir -p /var/log/remotelabz
 # Install packages
 echo -n "📦 Installing required packages... "
+debug "Running apt-get to grab required packages..."
 apt-get update >> "${INSTALL_LOG}" 2>&1
 apt-get install -y apache2 php zip unzip php-curl php-xdebug php-xml qemu libxml2-utils openvswitch-switch git python3 python3-pip >> "${INSTALL_LOG}" 2>&1
 echo "OK ✔️"
@@ -91,6 +108,7 @@ if ! [ $(command -v composer) ]; then
     echo "OK ✔️"
 else
   echo "Composer is already installed! Skipping... ✔️"
+  warning "Not installing Composer because it is done already."
 fi
 
 echo -n "🎶 Downloading Composer packages... "
@@ -104,17 +122,20 @@ echo "OK ✔️"
 chown -R www-data:www-data "${REMOTELABZ_WORKER_PATH}"/var
 
 # Folders
+debug "Creating images folder if it does not exists already..."
 mkdir -p /opt/remotelabz/images
 
 # Websockify
 echo -n "📡 Installing WebSockify... "
 if ! [ $(command -v websockify) ]; then
+    debug "Installing WebSockify..."
     pip3 install setuptools >> "${INSTALL_LOG}" 2>&1
     git clone https://github.com/novnc/websockify.git /opt/remotelabz/websockify >> "${INSTALL_LOG}" 2>&1
     (cd /opt/remotelabz/websockify/ && python3 setup.py install) >> "${INSTALL_LOG}" 2>&1
     echo "OK ✔️"
 else
   echo "WebSockify is already installed! Skipping... ✔️"
+  warning "Not installing WebSockify because it is done already."
 fi
 chown -R www-data:www-data /opt/remotelabz
 
